name: "🌌 Cosmic Contribution"
description: "Propose lore, science ideas, UX concepts, code improvements, or any contribution to Cosmic Origins."
title: "[Contribution] "
labels: ["contribution"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing to Cosmic Origins!  
        Use this template for:
        - Lore additions  
        - Worldbuilding ideas  
        - Scientific proposals  
        - UX / visual concepts  
        - Code improvements  
        - Documentation updates  
        - Anything that expands or improves the project  

        Be creative, be clear, be cosmic.

  - type: input
    id: topic
    attributes:
      label: "Contribution Topic"
      description: "What area does this relate to? (e.g., Lore, Physics Model, UI Concept, Chapter 2)"
      placeholder: "Example: Lore — Origin of the Nebula Seraphis"
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: "Describe your idea or contribution in 2–3 sentences."
      placeholder: "What is the core idea you want to add or improve?"
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: "Proposed Details"
      description: "Add specifics: concepts, diagrams, pseudocode, story elements, UI sketches, data models, etc."
      placeholder: "Explain the details of your contribution."
    validations:
      required: false

  - type: textarea
    id: impact
    attributes:
      label: "Expected Impact"
      description: "How does this improve the project? (lore depth, realism, UX, performance, clarity, maintainability)"
      placeholder: "Describe the value this contribution brings."
    validations:
      required: false

  - type: textarea
    id: testing
    attributes
